/* t_randsign.f -- translated by f2c (version 19980913).
   You must link the resulting object file with the libraries:
	-lf2c -lm   (in that order)
*/

#include "f2c.h"

/* $Procedure      T_RANDSIGN ( Random sign ) */
integer t_randsign__(integer *seed)
{
    /* System generated locals */
    integer ret_val;

    /* Local variables */
    extern doublereal t_urand__(integer *);

/* $ Abstract */

/*     Return a psudorandom -1 or 1. */

/* $ Disclaimer */

/*     THIS SOFTWARE AND ANY RELATED MATERIALS WERE CREATED BY THE */
/*     CALIFORNIA INSTITUTE OF TECHNOLOGY (CALTECH) UNDER A U.S. */
/*     GOVERNMENT CONTRACT WITH THE NATIONAL AERONAUTICS AND SPACE */
/*     ADMINISTRATION (NASA). THE SOFTWARE IS TECHNOLOGY AND SOFTWARE */
/*     PUBLICLY AVAILABLE UNDER U.S. EXPORT LAWS AND IS PROVIDED "AS-IS" */
/*     TO THE RECIPIENT WITHOUT WARRANTY OF ANY KIND, INCLUDING ANY */
/*     WARRANTIES OF PERFORMANCE OR MERCHANTABILITY OR FITNESS FOR A */
/*     PARTICULAR USE OR PURPOSE (AS SET FORTH IN UNITED STATES UCC */
/*     SECTIONS 2312-2313) OR FOR ANY PURPOSE WHATSOEVER, FOR THE */
/*     SOFTWARE AND RELATED MATERIALS, HOWEVER USED. */

/*     IN NO EVENT SHALL CALTECH, ITS JET PROPULSION LABORATORY, OR NASA */
/*     BE LIABLE FOR ANY DAMAGES AND/OR COSTS, INCLUDING, BUT NOT */
/*     LIMITED TO, INCIDENTAL OR CONSEQUENTIAL DAMAGES OF ANY KIND, */
/*     INCLUDING ECONOMIC DAMAGE OR INJURY TO PROPERTY AND LOST PROFITS, */
/*     REGARDLESS OF WHETHER CALTECH, JPL, OR NASA BE ADVISED, HAVE */
/*     REASON TO KNOW, OR, IN FACT, SHALL KNOW OF THE POSSIBILITY. */

/*     RECIPIENT BEARS ALL RISK RELATING TO QUALITY AND PERFORMANCE OF */
/*     THE SOFTWARE AND ANY RELATED MATERIALS, AND AGREES TO INDEMNIFY */
/*     CALTECH AND NASA FOR ALL THIRD-PARTY CLAIMS RESULTING FROM THE */
/*     ACTIONS OF RECIPIENT IN THE USE OF THE SOFTWARE. */

/* $ Required_Reading */

/*     None. */

/* $ Keywords */

/*     MATH */
/*     NUMBERS */

/* $ Declarations */
/* $ Brief_I/O */

/*     Variable  I/O  Description */
/*     --------  ---  -------------------------------------------------- */
/*     SEED      I-O  Seed for random number generation. */

/*     The function returns either 1 or -1. */

/* $ Detailed_Input */

/*     SEED           is a seed for the random number generator. On the */
/*                    first call to T_URAND, SEED should be set equal to */
/*                    a negative number.  After the first call, SEED */
/*                    should not be modified by the caller, except to */
/*                    start a new sequence of random numbers. */

/* $ Detailed_Output */

/*     SEED           is the seed value to be used as input on the next */
/*                    call to T_URAND to produce the next random number */
/*                    in the sequence. */

/*     The function returns values that are approximately uniformly */
/*     distributed over the open interval (0, 1). */

/* $ Parameters */

/*     None. */

/* $ Exceptions */

/*     Error free. */

/* $ Files */

/*     None. */

/* $ Particulars */

/*     Please see T_URAND for more details. */

/* $ Examples */

/*     None. */

/* $ Restrictions */

/*     1) Users must verify that the pseudo-random number sequences */
/*        generated by this routine are suitable for their applications. */

/* $ Literature_References */

/*     None. */

/* $ Author_and_Institution */

/*     S.C. Krening   (JPL) */

/* $ Version */

/* -    Testutil Version 1.0.0, 6-JAN-2012 (SCK) */

/* -& */

/*     Other functions */


/*     Local parameters */


/*     Call T_URAND to retrieve a random number between 0 and 1. */
/*     If the random number is greater than or equal to BND, return 1. */
/*     Otherwise, return -1. */

    if (t_urand__(seed) >= .5) {
	ret_val = 1;
    } else {
	ret_val = -1;
    }
    return ret_val;
} /* t_randsign__ */

